export default {
  TOKEN_IS_INVALID: "Token is invalid",
  LOGIN_SUCCESSFULLY: "Login successfully!",
  ARTICLE_CREATE_SUCCESS: "Article created",
  ARTICLE_UPDATE_SUCCESS: "Article updated",
  ARTICLE_DELETE_SUCCESS: "Article deleted",
  ARTICLES_LIST_UPDATED: "Updated",
  UNKNOWN_ERROR: "Unknown error.",
  GET_DATA_ERROR: "Error get data.",
  TITLE_ARTICLES: "Articles",
  TITLE_LOGIN: "Login",
  TITLE_REGISTER: "Register",
  INFO_NO_ARTICLES: "No articles yet.",
  TITLE_ADD_ARTICLE: "Add article",
  TITLE_EDIT_ARTICLE: "Edit article",
  TITLE_DELETE_ARTICLE: "Delete article",
  BUTTON_CLOSE: "Close",
  BUTTON_SAVE: "Save",
  BUTTON_DELETE: "Delete",
  BUTTON_LOGIN: "Login",
  BUTTON_REGISTER: "Register",
  BUTTON_ENTER_REGISTRATION_CODE: "Enter registration code",
};
