export default {
  ERROR_WHEN_TRY_TO_SEND_PASSPHRASE: "Error when try to send passphrase!",
  PASSPHRASE_WAS_SENT_SUCCESSFULLY: "Passphrase was sent successfully!",
  PASSPHRASE_IS_INVALID: "Passphrase is invalid",
  LOGIN_SUCCESSFULLY: "Login successfully!",
  ARTICLE_CREATE_SUCCESS: "Article created successfully!",
  ARTICLE_UPDATE_SUCCESS: "Article updated successfully!",
  ARTICLE_DELETE_SUCCESS: "Article deleted successfully!",
  ARTICLES_LIST_UPDATED: "List updated",
  UNKNOWN_ERROR: "Unknown error.",
  GET_DATA_ERROR: "Error get data.",
  TITLE_ARTICLES: "Articles",
  TITLE_LOGIN: "Login",
  TITLE_REGISTER: "Register",
  INFO_NO_ARTICLES: "No articles yet.",
  TITLE_ADD_ARTICLE: "Add article",
  TITLE_EDIT_ARTICLE: "Edit article",
  TITLE_DELETE_ARTICLE: "Delete article",
  BUTTON_CLOSE: "Close",
  BUTTON_SAVE: "Save",
  BUTTON_DELETE: "Delete",
};
